# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  Github: https://github.com/peakchen90
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Miscellaneous
google_analytics:
favicon: /logo.jpg
